
name: post_check trigger
permissions: read-all
on:
  check_run:
    types: [rerequested, completed]

jobs:
  trigger:
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    steps:
      - name: Build ğŸ”§ & Test ğŸ”
        run: "echo it works!"
